config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do  
    get 'admin', to: 'admin#index'
    get 'admin/posts'
    get 'admin/comments'
    get 'admin/users'
    get 'admin/show_post/:id', to: 'admin#show_post', as: 'admin_post'
  end

  get 'search', to: "search#index"
  get 'users/profile'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'u/:id', to: 'users#profile', as: 'user'

  # /posts/1/comments/4
  resources :posts do
    resources :comments
  end


  get 'about', to: 'pages#about'
  get 'posts', to: 'posts#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @query = Post.includes(:user, :rich_text_body).ransack(params[:q])
    @posts = @query.result(distinct: true)
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_form.html.erb
<%= search_form_for(@query, url: search_path, method: :get, class:'d-flex') do |f| %>
    <%= f.search_field :title_or_content_body_or_user_email_or_user_name_i_cont_any, 
    placeholder: "Search...",
    class: "form-control me-2",
    style: "background-color: #ffd21d;" %>
    <%= f.submit "Search", class: "btn btn-outline-warning" %>
<% end %>

app/views/search/index.html.erb
<h1 class="tet-center"><%= pluralize(@posts.count, "Result") %></h1>


<div class="container">
    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th><%= sort_link(@query, :title, "Title", default_order: :asc) %></th>
                <th><%= sort_link(@query, :body, "Blog Content") %></th>
                <th><%= sort_link(@query, :user_name, "Users") %></th>
            </tr>
        </thead>
        <tbody>
            <% @posts.each do |post| %>
            <tr>
                <td><%= link_to post.title, post %></td>
                <td><%= post.body.to_plain_text.truncate_words(25) %></td>
                <td><%= link_to post.user.name, post.user %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>