config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do  
    get 'admin', to: 'admin#index'
    get 'admin/posts'
    get 'admin/comments'
    get 'admin/users'
    get 'admin/show_post/:id', to: 'admin#show_post', as: 'admin_post'
  end

  get 'search', to: "search#index"
  get 'users/profile'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'u/:id', to: 'users#profile', as: 'user'

  # /posts/1/comments/4
  resources :posts do
    resources :comments
  end


  get 'about', to: 'pages#about'
  get 'posts', to: 'posts#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, counter_cache: true
  belongs_to :user
  has_rich_text :body

  after_create_commit :notify_recepient
  before_destroy :cleanup_notifications
  has_noticed_notifications model_name: 'Notification'

  private

  def notify_recepient
    return if post.user == user
    CommentNotification.with(comment: self, post: post).deliver_later(post.user)
  end

  def cleanup_notifications
    notifications_as_comment.destroy_all
  end

end

app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
    extend FriendlyId
    validates :title, presence: true, length: { minimum: 5, maximum: 50 }
    validates :body, presence: true
    belongs_to :user
    has_many :comments, dependent: :destroy

    has_rich_text :body
    has_one :content, class_name: 'ActionText::RichText', as: :record, dependent: :destroy

    has_noticed_notifications model_name: 'Notification'
    has_many :notifications, through: :user

    friendly_id :title, use: %i[slugged history finders]

    def should_generate_new_friendly_id?
        title_changed? || slug.blank?
      end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, as: :recipient, dependent: :destroy

  enum role: [:user, :admin]
  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= :user
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index;
  end

  def posts
    @posts = Post.all.includes(:user)
  end

  def comments;
  end

  def users;
  end

  def show_post
    @post = Post.includes(:user, comments: [:user, :rich_text_body]).find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_notifications, if: :current_user
    before_action :set_query

    def set_query
        @query = Post.ransack(params[:q])
    end

    private

    def set_notifications
        notifications = Notification.includes(:recipient).where(recipient: current_user).newest_first.limit(9)
        @unread = notifications.unread
        @read = notifications.read
      end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_post

    def create
        @comment = @post.comments.create(comment_params)
        @comment.user = current_user

        if @comment.save
            flash[:notice] = "Comment has been created"
            redirect_to post_path(@post)
        else
            flash[:alert] = "Comment has not been created"
            redirect_to post_path(@post)
        end
    end

    def update
        @comment = @post.comments.find(params[:id])
        
        respond_to do |format|
            if @comment.update(comment_params)
                format.html { redirect_to post_url(@post), notice: 'Comment has been updated'}
            else
                format.html { redirect_to post_url(@post), alert: 'Comment was not udpated!'}
            end
        end
    end

    def destroy
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end

    private

    def set_post
        @post = Post.find(params[:post_id])
    end

    def comment_params
        params.require(:comment).permit(:body)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[show index]
  # GET /posts or /posts.json
  def index
    @posts = Post.all.includes(:user, :rich_text_body).order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.update(views: @post.views + 1)
    @comments = @post.comments.includes(:user, :rich_text_body).order(created_at: :desc)
    mark_notifications_as_read
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])

      redirect_to @post, status: :moved_permanently if params[:id] != @post.slug
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end

    def mark_notifications_as_read
      if current_user
        notifications_to_mark_as_read = @post.notifications_as_post.where(recipient: current_user)
        notifications_to_mark_as_read.update_all(read_at: Time.zone.now)
      end
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @query = Post.includes(:user, :rich_text_body).ransack(params[:q])
    @posts = @query.result(distinct: true)
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  def profile
    @user.update(views: @user.views + 1)
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/_link.html.erb
<%= link_to resource.name.capitalize, url_for([:admin, resource]), class:'btn btn-secondary' %>

app/views/admin/_nav_links.html.erb
<div class="container text-center">
    <p>
    <%= link_to "Admin", admin_path %><%= " > #{params[:action].capitalize}" unless params[:action].eql?("index") %>
    <div class="btn-group">
        <%= render "admin/link", resource: Post %>
        <%= render "admin/link", resource: Comment %>
        <%= render "admin/link", resource: User %>
    </div>
    </div>

app/views/admin/comments.html.erb
<div class="container">
    <h1 class="text-center">Administrator</h1>
    <%= render 'admin/nav_links' %>
</div>

app/views/admin/index.html.erb
<div class="container">
    <h1 class="text-center">Administrator</h1>
    <%= render 'admin/nav_links' %>
</div>

app/views/admin/posts.html.erb
<div class="container">
    <h1 class="text-center">Administrator</h1>
    <%= render 'admin/nav_links' %>
    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col"><Post/th>
                <th scope="col">Author</th>
                <th scope="col">Comments</th>
            </tr>
        </thead>
        <tbody>
            <% @posts.each do |post| %>
            <tr>
                <th scope="row"><%= post.id %></th>
                <td><%= link_to post.title.truncate(15), admin_post_path(post) %></td>
                <td><%= post.user.name %></td>
                <td><%= pluralize(post.comments.size, "Comment") %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/admin/show_post.html.erb
<div class="container">
    <h1 class="text-center">Administrator</h1>
    <%= render "admin/nav_links" %>
    <div class="text-center md-5">
        <div class="btn-group">
            <%= link_to "Edit", edit_post_path(@post), class:"btn btn-warning" %>
            <%= button_to "Delete", @post, method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-danger" %>
        </div>
    </div>
    <div class="row mt-1">
        <p>
            <strong>Title:</strong><%= @post.title %>
        </p>
    </div>
    <div class="row mt-1">
    <p>
        <strong>Views:</strong><%= @post.views %>
    </p>
    </div>
    <div class="row mt-1">
    <p>
        <strong>Author:</strong>
        <%= "#{@post.user.email} | #{@post.user.name} | #{pluralize(@post.user.views, "View")}" %>
    </p>
    </div>
    <div class="rot mt-1">
        <strong>Body:</strong><%= @post.body %>
    </div>
    <div class="row mt-1">
        <strong><%= pluralize(@post.comments.count, "Comment") %>:</strong>
        <% @post.comments.each do |comment| %>
            <div class="row mt-1">
                <%= comment.user.name %>
                <%= comment.body %>
            </div>
        <% end %>
    </div>
</div>

app/views/admin/users.html.erb
<div class="container">
    <h1 class="text-center">Administrator</h1>
    <%= render 'admin/nav_links' %>

    
</div>

app/views/layouts/_alerts.html.erb
<% if notice  %> 
<p class="notice"><%= notice %></p>
<% elsif alert %>
<p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-custom navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "ZillaBlog", root_path, class:'navbar-brand yellow-text' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon" style="background-color: #ffd21d;"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:'nav-link yellow-text' %>
        </li>
        <li class="nav-item">
        <%= link_to "Posts", posts_path, class:'nav-link yellow-text' %>
        </li>
        <li class="nav-item">
        <%= link_to "About", about_path, class:'nav-link yellow-text' %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <%= render 'search/form' %>
        <%= render 'layouts/notifications' %>
        <%= render 'user/session_manager' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notification.html.erb
<li class="dropdown-item">
<%= link_to notification.to_notification.message, notification.to_notification.url %>
</li>

app/views/layouts/_notifications.html.erb
<% if current_user %>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="badge rounder-pill bg-danger">
                <%= @unread.count >= 9 ? "9+" : @unread.count %> <i class="bi bi-bell-fill"></i>
            </span>
        </a>
        <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
        <% @unread.each do |notification| %>
           <%= render 'layouts/notification', notification: notification %>
        <% end %>
        <% if @read.count > 0 && @unread.count > 0 %>
            <li>
                <hr class="dropdown-divider">
            </li>
        <% elsif @read.count + @unread.count == 0 %>
            <li class="dropdown-item">
                No notifications yet.
            </li>
        <% end %>
        <% @read.each do |notification| %>
           <%= render 'layouts/notification', notification: notification %>
        <% end %>
        </ul>
    </li>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZillaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header>
  <%= render 'layouts/navbar' %>
  <%= render 'layouts/alerts' %>
  </header>
  <main>
    <%= yield %>

  </main>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>
<%= link_to "Home", root_path %>

app/views/pages/home.html.erb
<div class="container">
    <h1>My personal homepage</h1>
    <p>Find me in app/views/pages/home.html.erb</p>
    <%= link_to "About", about_path, class:"btn btn-secondary" %>
    <%= link_to "Blog", posts_path, class:"btn btn-warning" %> 
</div>