config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do  
    get 'admin', to: 'admin#index'
    get 'admin/posts'
    get 'admin/comments'
    get 'admin/users'
    get 'admin/show_post/:id', to: 'admin#show_post', as: 'admin_post'
  end

  get 'search', to: "search#index"
  get 'users/profile'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'u/:id', to: 'users#profile', as: 'user'

  # /posts/1/comments/4
  resources :posts do
    resources :comments
  end


  get 'about', to: 'pages#about'
  get 'posts', to: 'posts#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/post.rb
class Post < ApplicationRecord
    extend FriendlyId
    validates :title, presence: true, length: { minimum: 5, maximum: 50 }
    validates :body, presence: true
    belongs_to :user
    has_many :comments, dependent: :destroy

    has_rich_text :body
    has_one :content, class_name: 'ActionText::RichText', as: :record, dependent: :destroy

    has_noticed_notifications model_name: 'Notification'
    has_many :notifications, through: :user

    friendly_id :title, use: %i[slugged history finders]

    def should_generate_new_friendly_id?
        title_changed? || slug.blank?
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[show index]
  # GET /posts or /posts.json
  def index
    @posts = Post.all.includes(:user, :rich_text_body).order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.update(views: @post.views + 1)
    @comments = @post.comments.includes(:user, :rich_text_body).order(created_at: :desc)
    mark_notifications_as_read
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])

      redirect_to @post, status: :moved_permanently if params[:id] != @post.slug
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end

    def mark_notifications_as_read
      if current_user
        notifications_to_mark_as_read = @post.notifications_as_post.where(recipient: current_user)
        notifications_to_mark_as_read.update_all(read_at: Time.zone.now)
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class:"yellow-bg" %>
  </div>

  <div class="form-control yellow-bg">
    <%= form.label :body, style: "display: block" %>
    <%= form.rich_text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="container test-bg" style="width: 49%;">
<div id="<%= dom_id post %>" >
  <p>
    <strong>Title:</strong>
    <h2><%= post.title %></h1>
    <h4>posted by <%= link_to post.user.name, user_path(post.user) %>
    <h6><%= pluralize(post.views, "view") %></h6>
  </p>

  <div>
  <p>
    <%= raw post.body.to_plain_text %>
  </p>
  </div>

  <p>
  <%= link_to "Show this post", post %>
  </p>

</div>
</div>

app/views/posts/edit.html.erb
<div class="container">
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
<h1>Posts</h1>

<div id="posts" class="posts-3-in-row ">
  <% @posts.each do |post| %>
    <%= render post %>
  <% end %>
</div>


<%= link_to "New post", new_post_path %>
</div>

app/views/posts/new.html.erb
<div class="container">
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>
</div>

app/views/posts/show.html.erb
<div class="container">
<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>
</div>

<div class="container">
  <%= render 'comments/form', post: @post, comment: @post.comments.build, submit_label: "Reply" %>
  <% @comments.each do |comment| %>
    <%= render 'comments/comment', 
    post: @post, 
    comment: comment %>
  <% end %>
</div>